name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github_token:
    required: true
    description: 'GitHub token'
  message:
    required: true
    description: 'message'  
  within_hours:
    required: true
    description: 'within hours'  
runs:
  using: 'node12'
  main: 'dist/index.js'
